[package]
name = "volley"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "47.0.0"
arrow-flight = "47.0.0"
futures = "0.3.28"
parquet = "47.0.0"
tokio = "1.32.0"
tonic = "0.10.2"
